server:
  port: 8090
  servlet:
    context-path: /auth-service
spring:
  application:
    name: auth-service
  config:
    import: configserver:http://localhost:8888
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud_test
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.ddl-auto: update
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect
      hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  jackson:
    default-property-inclusion: NON_NULL
jwt:
  secret: AvHGRK8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadweheufHNyG
  expiration: 3600000