server:
  host: localhost
  port: 8080
spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  config:
    import: configserver:http://localhost:8888
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.web: DEBUG
    org.springframework.http.server.reactive: DEBUG