# Server Configuration
server:
  port: 8081  # Defines the port on which the inventory-service will run


# Spring Application Configuration
spring:
  application:
    name: inventory-service  # Name of the microservice (used for service discovery and configuration)

  # Spring Cloud Config Server Configuration
  config:
    import: configserver:http://localhost:8888  # Fetches configurations from the Config Server running on port 8888
