server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sunilos/SpringCloud.git
          search-paths: config          
          clone-on-start: true     
