# Server configuration
server:
  port: 8082  # Defines the port on which the payment-service will run

# Spring application configuration
spring:
  application:
    name: payment-service  # Name of the microservice (used for service discovery)

  # Spring Cloud Config Server
  config:
    import: configserver:http://localhost:8888  # Fetches configurations from the Config Server running on port 8888
